name: chat_doc
description: A new Chat Doc project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Networking
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
  dartz: ^0.10.1
  retrofit: ^3.0.1+1
  connectivity_plus: ^2.3.6+1
  graphql: ^5.1.1
  # State management
  flutter_bloc: ^8.1.1
  # User interface
  lottie: ^1.4.3
  flutter_svg: ^1.1.3
  flutter_screenutil: ^5.5.4
  # Annotation
  meta: any
  # Data type
  equatable: ^2.0.5
  # Language
  easy_localization: ^3.0.1
  localstore: ^1.2.3
  shared_preferences: ^2.0.15
  eva_icons_flutter: ^3.1.0
  pin_code_fields: ^7.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  json_annotation: ^4.6.0
  json_serializable: ^6.5.1
  retrofit_generator: ^4.0.3+1
  build_runner: ^2.2.0
  mockito: ^5.3.0
  analyzer: ^4.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/locales/
    - assets/animations/

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700
        - asset: assets/fonts/Comfortaa-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Comfortaa-Medium.ttf
          weight: 500
        - asset: assets/fonts/Comfortaa-Regular.ttf
          weight: 400
        - asset: assets/fonts/Comfortaa-Light.ttf
          weight: 300